# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "e96dd6f2b07b59eaa0c33cb3ee9dc6de"
application_url = "https://tcs-booking.vercel.app"
embedded = true
name = "TCS BOOKING"

[access_scopes]
# See SCOPES.md for justification of each scope
scopes = "read_orders,write_orders,read_fulfillments,write_fulfillments,read_merchant_managed_fulfillment_orders,write_merchant_managed_fulfillment_orders"

[webhooks]
api_version = "2026-07"

  [[webhooks.subscriptions]]
  uri = "/webhooks/app/uninstalled"
  topics = [ "app/uninstalled" ]

  [[webhooks.subscriptions]]
  uri = "/webhooks/app/scopes_update"
  topics = [ "app/scopes_update" ]

  [[webhooks.subscriptions]]
  uri = "/webhooks/orders/create"
  topics = [ "orders/create" ]

  [[webhooks.subscriptions]]
  uri = "/webhooks/orders/updated"
  topics = [ "orders/updated" ]

  [[webhooks.subscriptions]]
  uri = "/webhooks/orders/cancelled"
  topics = [ "orders/cancelled" ]

  [[webhooks.subscriptions]]
  uri = "/webhooks/customers/data_request"
  topics = [ "customers/data_request" ]

  [[webhooks.subscriptions]]
  uri = "/webhooks/customers/redact"
  topics = [ "customers/redact" ]

  [[webhooks.subscriptions]]
  uri = "/webhooks/shop/redact"
  topics = [ "shop/redact" ]

[auth]
redirect_urls = [
  "https://tcs-booking.vercel.app/auth/callback",
  "https://tcs-booking.vercel.app/auth/shopify/callback"
]

[build]
automatically_update_urls_on_dev = true
